config/routes.rb
Apptracksys::Application.routes.draw do

  get "home/index"
    devise_for :jobseekers, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
    devise_for :employers

  root 'home#index'

end

app/models/employer.rb
class Employer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/jobseeker.rb
class Jobseeker < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :omniauthable, :rememberable, :trackable, :validatable

  def self.connect_to_linkedin(auth, signed_in_resource=nil)
    jobseeker = Jobseeker.where(:provider => auth.provider, :uid => auth.uid).first
    if jobseeker
      return jobseeker
    else
      registered_jobseeker = Jobseeker.where(:email => auth.info.email).first
      if registered_jobseeker
        return registered_jobseeker
      else

        jobseeker = Jobseeker.create(name:auth.info.first_name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.info.email,
                            password:Devise.friendly_token[0,20],
                          )
      end
    end
  end   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def linkedin
		auth = env["omniauth.auth"]
		@jobseeker = Jobseeker.connect_to_linkedin(request.env["omniauth.auth"], current_jobseeker)
		if @jobseeker.persisted?
			flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
				sign_in_and_redirect @jobseeker, :event => :authentication
		else
			session["devise.linkedin_uid"] = request.env["omniauth.auth"]
			redirect_to_new_user_registration_url
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/employer/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/jobseeker/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_header.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
                <a class="navbar-brand logo-nav" href="#">
                    <img src="http://placehold.it/150x75&text=Logo">
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <% if employer_signed_in? %>
  						<li>Welcome <%= current_employer.email %></li>
  						<li><%= link_to 'Logged In [click to logout]', destroy_employer_session_path, :method => :delete %></li>
					<% else %>
 						<li><%= link_to 'Employer Login', new_employer_session_path %></li>
					<% end %>
                    <% if jobseeker_signed_in? %>
						<li>Welcome <%= current_jobseeker.email %></li>
  						<li><%= link_to 'Logged In [click to logout]', destroy_jobseeker_session_path, :method => :delete %></li>
					<% else %>
  						<li class="dropdown">
                   			<a href="#" class="dropdown-toggle">Jobseeker <b class="caret"></b></a>
	                   		<ul class="dropdown-menu">
          						<li><%= link_to 'Login', new_jobseeker_session_path %></li>
								<li><%= link_to image_tag("linkedin-signin.png"),jobseeker_omniauth_authorize_path(:linkedin) %></li>
          					</ul>
                    	</li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project "Otto"</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript"> $(document).ready(function () { $('.dropdown-toggle').dropdown(); }); </script>

</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
        <div class="row">
            <div class="col-lg-12">
                <%= yield %>
            </div>
        </div>

    </div>
</body>
</html>